Second part book-store - added dto, controller, mapstrust and mappers. Added new methods to service and repository.
yevhenkukharchuk/online-book-store pull request #2
Opened 2023-10-17 17:09 UTC by yevhenkukharchuk

2023-10-18 12:50 UTC, Cayman4010 commented on src/main/java/yevhen/bookstore/controller/BookController.java
> +    @GetMapping(value = "/{id}")
You can use just `@GetMapping("/{id}")`, but I think it`s OK too

2023-10-18 12:52 UTC, Cayman4010 commented on src/main/java/yevhen/bookstore/dto/BookDto.java
> +}
You can use records in Dtos

2023-10-18 12:53 UTC, Cayman4010 commented on src/main/java/yevhen/bookstore/mapper/BookMapper.java
> +@Mapper(config = MapperConfig.class)
You can add config just here in ()

2023-10-18 12:57 UTC, Cayman4010 commented on src/main/java/yevhen/bookstore/repository/impl/BookRepositoryImpl.java
> +            throw new RuntimeException("Can't save book:" + book, e);
May be, you need too use custom exception like DataProcessingException insted RuntimeException?

2023-10-18 13:01 UTC, Cayman4010 commented on src/main/java/yevhen/bookstore/repository/impl/BookRepositoryImpl.java
> +            return entityManager.createQuery("SELECT b FROM Book b", Book.class)
may be, you should return EntityNotFoundException in case if database is empty?

2023-10-18 13:02 UTC, Cayman4010 commented on src/main/java/yevhen/bookstore/repository/impl/BookRepositoryImpl.java
> +            return entityManager.find(Book.class, id);
and here

2023-10-18 13:03 UTC, Cayman4010 commented on src/main/java/yevhen/bookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(book);
I think it can be inline variable

2023-10-18 13:06 UTC, Cayman4010 commented on src/main/java/yevhen/bookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.save(book));
and here (see lower), but your way seems more readable

2023-10-18 13:07 UTC, Cayman4010 approved these changes

2023-10-24 09:00 UTC, liliia-ponomarenko requested changes
Good job! Let’s  fix a few mistakes ;)

2023-10-24 09:00 UTC, liliia-ponomarenko commented on src/main/java/yevhen/bookstore/config/MapperConfig.java
> +)
you can use Mapper annotation in your Book mapper class instead  this class

2023-10-24 09:00 UTC, liliia-ponomarenko commented on src/main/java/yevhen/bookstore/controller/BookController.java
> +@RequestMapping(value = "/api/books")
```suggestion
@RequestMapping("/books")
```

2023-10-24 09:00 UTC, liliia-ponomarenko commented on src/main/java/yevhen/bookstore/mapper/BookMapper.java
> +@Mapper(config = MapperConfig.class)
agree

2023-10-24 09:00 UTC, liliia-ponomarenko commented on src/main/java/yevhen/bookstore/model/Book.java
> +
```suggestion
```

2023-10-24 09:00 UTC, liliia-ponomarenko commented on src/main/java/yevhen/bookstore/repository/BookRepository.java
> +    Book getBookById(Long id);
```suggestion
    Book findById(Long id);
```

2023-10-24 09:00 UTC, liliia-ponomarenko commented on src/main/java/yevhen/bookstore/repository/impl/BookRepositoryImpl.java
> +        } catch (EntityNotFoundException e) {
```suggestion
        } catch (Exception e) {
```

2023-10-24 09:00 UTC, liliia-ponomarenko commented on src/main/java/yevhen/bookstore/repository/impl/BookRepositoryImpl.java
> +            return entityManager.createQuery("SELECT b FROM Book b", Book.class)
```suggestion
            return entityManager.createQuery("FROM Book ", Book.class)
```

2023-10-24 09:00 UTC, liliia-ponomarenko commented on src/main/java/yevhen/bookstore/repository/impl/BookRepositoryImpl.java
> +        } catch (EntityNotFoundException e) {
the same

2023-10-24 09:00 UTC, liliia-ponomarenko commented on src/main/java/yevhen/bookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.save(book));
agree

2023-11-04 23:48 UTC, NazarSmith228 approved these changes
LGTM, but please address my remarks

2023-11-04 23:48 UTC, NazarSmith228 commented on src/main/java/yevhen/bookstore/dto/BookDto.java
> +) {}
```suggestion
        String coverImage) {
}
```

2023-11-04 23:48 UTC, NazarSmith228 commented on src/main/java/yevhen/bookstore/dto/CreateBookRequestDto.java
> +) {}
```suggestion
        String coverImage) {
}
```

2023-11-04 23:48 UTC, NazarSmith228 commented on src/main/java/yevhen/bookstore/repository/impl/BookRepositoryImpl.java
> +        } catch (RuntimeException e) {
```suggestion
        } catch (Exception e) {
```

2023-11-04 23:48 UTC, NazarSmith228 commented on src/main/java/yevhen/bookstore/repository/impl/BookRepositoryImpl.java
> +    public Book findById(Long id) {
shouldn't you use `Optional`?

2023-11-28 13:55 UTC, merged