05 - added data validation and GlobalExceptionHandler
yevhenkukharchuk/online-book-store pull request #5
Opened 2023-11-08 12:07 UTC by yevhenkukharchuk

2023-11-08 13:34 UTC, YuraNR requested changes

2023-11-08 13:34 UTC, YuraNR commented on src/main/java/yevhen/bookstore/dto/CreateBookRequestDto.java
> +        @NotNull
Will be better to use @NotBlank

2023-11-08 13:34 UTC, YuraNR commented on src/main/java/yevhen/bookstore/dto/CreateBookRequestDto.java
> +        @Min(0)
Also we need to use here @PositiveOrZero instead @Min(0)

2023-11-08 13:34 UTC, YuraNR commented on src/main/java/yevhen/bookstore/exception/CustomGlobalExceptionHandler.java
> +        errorMessage.put("status", HttpStatus.BAD_REQUEST);
errorMessage.put("timestamp", LocalDateTime.now());
errorMessage.put("status", HttpStatus.BAD_REQUEST);
we don't need it

2023-11-08 15:14 UTC, YuraNR approved these changes

2023-11-10 08:45 UTC, liliia-ponomarenko requested changes
Good job! Let’s  improve your solution)

2023-11-10 08:45 UTC, liliia-ponomarenko commented on pom.xml
> +        </dependency>
it is better to use spring-boot-starter-validation

2023-11-10 08:45 UTC, liliia-ponomarenko commented on src/main/java/yevhen/bookstore/controller/BookController.java
> +    public BookDto createBook(@RequestBody @Valid CreateBookRequestDto requestDto) {
You should  add Valid to the body of the update method

2023-11-10 08:45 UTC, liliia-ponomarenko commented on src/main/java/yevhen/bookstore/exception/CustomGlobalExceptionHandler.java
> +public class CustomGlobalExceptionHandler extends ResponseEntityExceptionHandler {
You also should handle EntityNotFoundException

2023-11-13 09:21 UTC, NazarSmith228 approved these changes
LGMT, but pls pay attention to my remarks

2023-11-13 09:21 UTC, NazarSmith228 commented on pom.xml
> +            <version>3.1.2</version>
you don't need to specify version here - it is taken from `spring-boot-starter-parent`

2023-11-13 09:21 UTC, NazarSmith228 commented on src/main/java/yevhen/bookstore/dto/CreateBookRequestDto.java
> +        @NotBlank
I guess you should use `@NotNull` with BigDecimal

2023-11-28 14:02 UTC, merged